# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c5ad9bfc6bd4441d45e9d90a7919ecd640a016b30fa239691714e52acef76192bd5fce7926aafab469db3fa9ce3472c38519d79ce260a95f39c7a13b40a37cc

test:
  secret_key_base: f1e69f9cba4a78bbf5fd61b2db057904d29acff925906f18d9f4021f5331b3f2e60ad0beaaedec490d4b25b6e7065c3405f3a8f3e6063badbbdc431e5128c8dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
